  
title = "LOWCODETALK"
baseURL = ""
languageCode = "en-us"
theme = "ananke"


DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/lowcodetalk_favicon.svg"
  site_logo = "/images/LOWCODETALK_LOGO.svg"
  description = "IT Pros and Citizen Developers has a larger role in the digitalization of a company than ever, and we wanna talk about it. What is 'Low or No Code' Solutions? How to use them? and more."
  facebook = ""
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2